version: '3'

services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/youapp

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
